package com.admost.reactnative;

public interface Constants {

  String ADMOST_INSTANCE_NOT_FOUND = "ADMOST_INSTANCE_NOT_FOUND";

  String ADMOST_INTERSTITIAL_ON_READY = "ADMOST_INTERSTITIAL_ON_READY";
  String ADMOST_INTERSTITIAL_ON_FAIL = "ADMOST_INTERSTITIAL_ON_FAIL";
  String ADMOST_INTERSTITIAL_ON_DISMISS = "ADMOST_INTERSTITIAL_ON_DISMISS";
  String ADMOST_INTERSTITIAL_ON_SHOWN = "ADMOST_INTERSTITIAL_ON_SHOWN";
  String ADMOST_INTERSTITIAL_ON_CLICKED = "ADMOST_INTERSTITIAL_ON_CLICKED";
  String ADMOST_INTERSTITIAL_ON_STATUS_CHANGED = "ADMOST_INTERSTITIAL_ON_STATUS_CHANGED";

  String ADMOST_REWARDED_ON_READY = "ADMOST_REWARDED_ON_READY";
  String ADMOST_REWARDED_ON_FAIL = "ADMOST_REWARDED_ON_FAIL";
  String ADMOST_REWARDED_ON_DISMISS = "ADMOST_REWARDED_ON_DISMISS";
  String ADMOST_REWARDED_ON_COMPLETE = "ADMOST_REWARDED_ON_COMPLETE";
  String ADMOST_REWARDED_ON_SHOWN = "ADMOST_REWARDED_ON_SHOWN";
  String ADMOST_REWARDED_ON_CLICKED = "ADMOST_REWARDED_ON_CLICKED";
  String ADMOST_REWARDED_ON_STATUS_CHANGED = "ADMOST_REWARDED_ON_STATUS_CHANGED";
}
